### ISSUE TITLE
Can verify show user info if it cannot confirm authenticity?

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/verify#102]
**Is your feature request related to a problem? Please describe.**
Following Quickstart v0.21.0 verify doesn't show user information from `jwt`  when it cannot validate it.

**Describe the solution you'd like**
Can `verify` display user identity information even if it is not trusted.

**Describe alternatives you've considered**

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

![image](https://user-images.githubusercontent.com/37595288/216709919-50e2dcb9-ce8b-4bf8-ba1c-17df301752a7.png)

**Comment by wasaga** [comment]
current quickstart docker-compose has to be updated for v0.21.0 in order to use verify as an example, to use namespace aliases similar to how it was addressed in the enterprise quickstart PR @ZPain8464

**Comment by ssveta7ak** [comment]
It is necessary to add a network alias to the docker-compose.yaml
```
version: "3"
networks:
  main: {}
services:
  pomerium:
    image: pomerium/pomerium:v0.21.0-rc2
    volumes:
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
    networks:
      main:
        aliases:
          - authenticate.localhost.pomerium.io  
  verify:
    image: pomerium/verify:latest
    expose:
      - 8000
    networks:
      main: {}
```

**Comment by desimone** [comment]
Agree. We should still show the payload's contents even if it's untrusted. 

We should probably give a little bit of advice as to _why_ the payload is untrusted, especially if we are using an obviously fake domain like `localhost.pomerium.com`.

**Comment by calebdoxsey** [comment]
This is not what I see locally. I see

<img width="648" alt="Screenshot 2023-02-07 at 4 09 29 PM" src="https://user-images.githubusercontent.com/395272/217387650-97e010b2-40ed-4530-8394-11dd1ddd9f0a.png">

**Comment by calebdoxsey** [comment]
From this PR: https://github.com/pomerium/verify/pull/84

**Comment by calebdoxsey** [comment]
Running `docker pull pomerium/verify:latest` fixes this for me.

**Comment by ZPain8464** [comment]
I had to include the `signing_key` to get the claims to show. This makes sense, but weren't we trying to eliminate that config var entirely? If not, I can include the steps to generate the singing key in the Quickstart.

**Comment by ssveta7ak** [comment]
Thank you, you were right - my `verify` image wasn't updated. I did `docker pull pomerium/verify:latest`, so the image is up to date for pomerium/pomerium:latest now. But it still doesn't work on my machine. I tested [Quickstart](https://deploy-preview-256--pomerium-docs.netlify.app/docs/quickstart) guide for Core using Docker and following all steps I  still have this problem.
![Screenshot from 2023-02-08 18-19-29](https://user-images.githubusercontent.com/37595288/217631433-d712ca5b-7f22-4c6f-84c0-7e4955db6ddf.png)

**docker-compose-yaml**
```
version: "3"
networks:
  main: {}
services:
  pomerium:
    image: pomerium/pomerium:v0.21.0-rc2
    volumes:
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
    networks:
      main:
        aliases:
          - authenticate.localhost.pomerium.io  

  ## https://verify.localhost.pomerium.io --> Pomerium --> http://verify
  verify:
    image: pomerium/verify:latest
    expose:
      - 8000
    networks:
      main: {}
```
**config.yaml**

```
authenticate_service_url: https://authenticate.localhost.pomerium.io
idp_provider: 'auth0'
idp_provider_url: 'https://dev-zecq6kxx.us.auth0.com'
idp_client_id: <>
idp_client_secret: <>
routes:
  - from: https://verify.localhost.pomerium.io
    to: http://verify:8000
    policy:
      - allow:
          or:
            - email:
                is: svetlana.rekuts@gmail.com
    pass_identity_headers: true
```
logs-verify
```
{"time":"2023-02-08T19:45:45Z","message":"KeyID: e409b79af9f77c7e724a32ad7c7ce042b37446bc2c8575fcecc33bc939b7b07f not found, fetching jwks endpoint: https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json"}
```
logs-pomerium
```
{"level":"info","service":"authorize","request-id":"fd18718e-ab7a-457b-80fe-b170e0cdcbbf","check-request-id":"fd18718e-ab7a-457b-80fe-b170e0cdcbbf","method":"GET","path":"/","host":"verify.localhost.pomerium.io","query":"","ip":"172.18.0.1","session-id":"d15a59fc-fa2e-451e-b58c-3c48933115ec","allow":true,"allow-why-true":["email-ok"],"deny":false,"deny-why-false":["valid-client-certificate-or-none-required"],"user":"auth0|6362f9a7f4d448159fc9a336","email":"svetlana.rekuts@gmail.com","time":"2023-02-08T19:45:45Z","message":"authorize check"}

{"level":"info","service":"envoy","upstream-cluster":"route-f3c0b48710aa7e9f","method":"GET","authority":"verify","path":"/","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","referer":"","forwarded-for":"172.18.0.1","request-id":"fd18718e-ab7a-457b-80fe-b170e0cdcbbf","duration":7.857033,"size":453,"response-code":200,"response-code-details":"via_upstream","time":"2023-02-08T19:45:45Z","message":"http-request"}
```

**Comment by ssveta7ak** [comment]
The user information still isn't displayed. I tested the Ingress Controller with the latest image `docker.io/pomerium/verify:sha-3030d6a`

![Screenshot from 2023-02-15 21-35-46](https://user-images.githubusercontent.com/37595288/219180939-324d4f22-ceda-44b6-acc8-834ff8149729.png)

**Comment by calebdoxsey** [comment]
The docker aliases setting was supposed to fix this error. I will attempt to go through the guide to reproduce this.

**Comment by calebdoxsey** [comment]
I was not able to reproduce this. The quickstart does not give me this error. It returns:

> TLS Certificate verification failed
> TLS certificate verification failed when verifying the JWT: x509: certificate signed by unknown authority

And shows the user info.

**Comment by wasaga** [comment]
```yaml
authenticate_service_url: https://authenticate.staging.pomerium.app

routes:
  - from: https://verify.localhost.pomerium.io
    to: https://verify.pomerium.com
    allow_any_authenticated_user: true
    pass_identity_headers: true
```

<img width="665" alt="image" src="https://user-images.githubusercontent.com/673131/235037438-2705580c-12fa-4c17-95d0-f6a3546dedfb.png">

**Comment by desimone** [comment]
Per https://github.com/pomerium/verify/issues/102#issuecomment-1526879147

Let's relax verification (by default) with a flag (if people want strict TLS verification).

**Comment by ssveta7ak** [comment]
Fixed. Checked on 
Core v0.20.0-277-g498bc82e + 498bc82e
Enterprise v0.20.0 + 9a9837b1 + 2023-04-28T16:11:49 + 01:00
